# Generated by Django 4.1.2 on 2022-10-15 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Время добавления')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('content', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('owner_pk', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=models.SET(1), to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=models.SET(1), related_name='nots', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
