# Generated by Django 4.1.2 on 2022-10-14 11:54

import apps.cars.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Время добавления')),
                ('registration_number', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Регистрационный номер')),
                ('region_code', models.PositiveSmallIntegerField(verbose_name='Код региона')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Последний осмотр')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.cars.models.Car.return_path_to_upload_avatar, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Время добавления')),
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='TypeOfApplication',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявок',
            },
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Время добавления')),
                ('time_to_execute', models.PositiveIntegerField(default=0, verbose_name='Время на выполнение')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность заявки')),
                ('status', models.CharField(choices=[('O', 'Ожидает рассмотрения менеджера'), ('OE', 'Ожидает подтверждение механика'), ('REP', 'Ремонтируется'), ('V', 'Выполнена'), ('P', 'Просрочена'), ('T', 'Отклонено')], default='O', max_length=3, verbose_name='Статус')),
                ('urgency', models.CharField(choices=[('N', 'Не срочно'), ('U', 'Срочно'), ('S', 'Очень срочно')], default='N', max_length=1, verbose_name='Cрочность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqs', to='cars.car', verbose_name='Машина')),
                ('engineer', models.ForeignKey(null=True, on_delete=models.SET(None), related_name='repair_reqs', to=settings.AUTH_USER_MODEL, verbose_name='Механик')),
                ('owner', models.ForeignKey(null=True, on_delete=models.SET(None), related_name='reqs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('type', models.ForeignKey(null=True, on_delete=models.SET(None), to='cars.typeofapplication', verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания ')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Время добавления')),
                ('start_date', models.DateField(verbose_name='Дата выдачи')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.cars.models.CarDocument.return_path_to_upload_doc, verbose_name='Копия')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='cars.car', verbose_name='Машина')),
                ('type', models.ForeignKey(on_delete=models.SET(None), to='base.doctype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Документ машины',
                'verbose_name_plural': 'Документы машины',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='cars', to='cars.carbrand', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
