# Generated by Django 4.1.2 on 2022-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Наименования')),
                ('car_or_user', models.CharField(choices=[('m', 'Человек'), ('c', 'Машина')], default='c', max_length=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
    ]
