version: '3.8'

networks:
  default:
    name: car_park_dev_network

services:
  dev_web:
    container_name: car_park_dev_web_container
    build: ../backend
    command: bash -c "
      python manage.py makemigrations         
      && python manage.py makemigrations base
      && python manage.py makemigrations account
      && python manage.py makemigrations cars
      && python manage.py migrate
      && python manage.py migrate base
      && python manage.py migrate account
      && python manage.py migrate cars
      && python manage.py collectstatic --no-input --clear
      && python manage.py initadmin
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ../backend/:/app/
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=very_secret_key

      - POSTGRES_NAME=dev_db
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=manager_password
      - POSTGRES_HOST=dev_db
      - POSTGRES_PORT=5432

      - DATABASE=postgres
    depends_on:
      - dev_db
    restart: always
    entrypoint: ./scripts/wait_db.sh


  dev_db:
    container_name: cara_park_dev_db_container
    image: postgres:latest
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=manager_password

volumes:
  dev_postgres_data:

#python manage.py makemigrations base
#&& python manage.py makemigrations account
#&& python manage.py makemigrations cars
#&& python manage.py migrate base
#&& python manage.py migrate account
#&& python manage.py migrate cars